export default [
  // TOGGLE
  { phrase: "activate", action: "activate" },
  { phrase: "deactivate", action: "deactivate" },
  // UI
  { phrase: "refresh", action: "refresh" },
  { phrase: "reload", action: "refresh" },
  { phrase: "dark", action: "toggledark" },
  { phrase: "grey", action: "togglegrey" },
  { phrase: "light", action: "togglelight" },

  //NAVIGATION
  { phrase: "index", action: "navigate", to: "/" },
  { phrase: "home", action: "navigate", to: "/" },
  { phrase: "dashboard", action: "navigate", to: "/" },
  { phrase: "analytics", action: "navigate", to: "/stats" },
  { phrase: "stats", action: "navigate", to: "/stats" },
  { phrase: "network", action: "navigate", to: "/stats" },
  { phrase: "security", action: "navigate", to: "/devices" },
  { phrase: "devices", action: "navigate", to: "/devices" },
  { phrase: "explore", action: "navigate", to: "/explore" },
  { phrase: "explor", action: "navigate", to: "/explore" },
  { phrase: "console", action: "navigate", to: "/terminal" },
  { phrase: "terminal", action: "navigate", to: "/terminal" },
  { phrase: "setting", action: "navigate", to: "/settings" },
  { phrase: "settings", action: "navigate", to: "/settings" },
  { phrase: "command", action: "navigate", to: "/commands" },
  { phrase: "commands", action: "navigate", to: "/commands" },

  //VOICE
  { phrase: "stop", action: "toggleVoice" },

  // SOS
  { phrase: "help", action: "triggerSOS" },
  { phrase: "sos", action: "triggerSOS" },
  { phrase: "silent", action: "triggerSilentSOS" },

  //TERMINAL
  { phrase: " ", action: "pass" },
  { phrase: "", action: "pass" },
  { phrase: "kali", action: "bootkali" },
  { phrase: "nokali", action: "killkali" },
  { phrase: "no kali", action: "killkali" },
  { phrase: "scan off", action: "stopScan" },
  { phrase: "scan stop", action: "stopScan" },


  // Scans - Full 18 Types
  { phrase: "option one", action: "executeScan", scanType: 1 },
  { phrase: "option 1", action: "executeScan", scanType: 1 },
  { phrase: "option two", action: "executeScan", scanType: 2 },
  { phrase: "option 2", action: "executeScan", scanType: 2 },
  { phrase: "option three", action: "executeScan", scanType: 3 },
  { phrase: "option 3", action: "executeScan", scanType: 3 },
  { phrase: "option four", action: "executeScan", scanType: 4 },
  { phrase: "option 4", action: "executeScan", scanType: 4 },
  { phrase: "option five", action: "executeScan", scanType: 5 },
  { phrase: "option 5", action: "executeScan", scanType: 5 },
  { phrase: "option six", action: "executeScan", scanType: 6 },
  { phrase: "option 6", action: "executeScan", scanType: 6 },
  { phrase: "option seven", action: "executeScan", scanType: 7 },
  { phrase: "option 7", action: "executeScan", scanType: 7 },
  { phrase: "option eight", action: "executeScan", scanType: 8 },
  { phrase: "option 8", action: "executeScan", scanType: 8 },
  { phrase: "option nine", action: "executeScan", scanType: 9 },
  { phrase: "option 9", action: "executeScan", scanType: 9 },
  { phrase: "option ten", action: "executeScan", scanType: 10 },
  { phrase: "option 10", action: "executeScan", scanType: 10 },
  { phrase: "option eleven", action: "executeScan", scanType: 11 },
  { phrase: "option 11", action: "executeScan", scanType: 11 },
  { phrase: "option twelve", action: "executeScan", scanType: 12 },
  { phrase: "option 12", action: "executeScan", scanType: 12 },
  { phrase: "option thirteen", action: "executeScan", scanType: 13 },
  { phrase: "option 13", action: "executeScan", scanType: 13 },
  { phrase: "option fourteen", action: "executeScan", scanType: 14 },
  { phrase: "option 14", action: "executeScan", scanType: 14 },
  { phrase: "option fifteen", action: "executeScan", scanType: 15 },
  { phrase: "option 15", action: "executeScan", scanType: 15 },
  { phrase: "option sixteen", action: "executeScan", scanType: 16 },
  { phrase: "option 16", action: "executeScan", scanType: 16 },
  { phrase: "option seventeen", action: "executeScan", scanType: 17 },
  { phrase: "option 17", action: "executeScan", scanType: 17 },
  { phrase: "option eighteen", action: "executeScan", scanType: 18 },
  { phrase: "option 18", action: "executeScan", scanType: 18 },
];
